### PR TITLE
Add Excimer extension

### PR DESCRIPTION
**Pull request by kdambekalns**
See https://www.mediawiki.org/wiki/Excimer for background information.

The extension can be enabled by setting the environment variable `PHP_EXCIMER_ENABLE=true`.

### CODE REVIEW

**Comment by kdambekalns** [comment]
To test:

```
docker build --build-arg PHP_VERSION=8.4.1 -t flownative/php:8.4.1 .
docker run --rm -it -e PHP_EXCIMER_ENABLE=true docker.io/flownative/php:8.4.1 bash

          PHP
          This Docker image was handcrafted for you
          by Flownative.         www.flownative.com

[info] syslog-ng: Starting ...
[info] syslog-ng: Logging mode is text
[info] syslog-ng: Running as process #11
[info] PHP-FPM: Initializing configuration ...
[info] PHP-FPM: Xdebug is disabled
[info] PHP-FPM: igbinary is disabled
[info] PHP-FPM: Excimer is enabled
[info] Supervisor: Starting ...
[info] Supervisor: Running as process #30
I have no name!@32657fc85862:/opt/flownative/php$ php -mi excimer

excimer

excimer support => enabled
excimer version => 1.2.3

Directive => Local Value => Master Value
excimer.default_max_depth => 1000 => 1000
```

**Comment by kitsunet** [comment]
IDK do we want this? Seems pretty small and obviously due to it's nature deeply integrates with PHP, I am skeptical if this is a good idea in terms of security and support?

**Comment by kdambekalns** [comment]
Given that this is

- in use at Wikipedia / MediaWiki for years (in production, see [blog post](https://calendar.perfplanet.com/2020/profiling-php-in-production-at-scale/) and [re-post](https://techblog.wikimedia.org/2021/03/03/profiling-php-in-production-at-scale/)) and
- Sentry uses it as it's [profiling solution for PHP](https://docs.sentry.io/platforms/php/profiling/)

I'd say it's a pretty safe bet. Plus, unless enabled, it doesn't even get loaded.

**Review by robertlemke — APPROVED** [review]
If it works, I'm fine with that.

**Pull request merged**
