### PR TITLE
Introduce igbinary support

### PR DESCRIPTION
**Pull request by robertlemke**

### CODE REVIEW

**Comment by kdambekalns** [comment]
After the introduction of igbinary, all caches that survive a deployment and use the `VariableFrontend` would be broken. This could be solved by a flush. With persistent caches... critical out-of-the-box might be the encryption key, but that uses a `StringFontend`.

I looked at the Flow code, and... um. This could really be a problem: https://github.com/neos/flow-development-collection/blob/0a19f923d959f6bc34ec61bc5ba7b673ed5478a3/Neos.Flow/Classes/Persistence/Aspect/PersistenceMagicAspect.php#L138

If I see it correctly, there the identity of Value Objects is "calculated", and if changed to/from igbinary, two identical VO would get different hashes... Who the heck came up with that? Ah, it was me 🤦♂️, see https://github.com/neos/flow-development-collection/commit/90cb65827c1550e9144e9f83b9231b430c106660

In a later change (https://github.com/neos/flow-development-collection/commit/9df151da7c6ef35d342d1c8063386741eef9afb0) this was noted:
> This *might* be breaking in the unlikely case where the initial hash calculation leads to the same hash as the new calculation, for different VOs. Besides, it might lead to duplicate VOs in the database because the "same" VO can become a new hash due to the changed hashing algorithm.

So, maybe even that is not really a problem (aside from duplicating some data?)

**Comment by robertlemke** [comment]
On the other hand, `igbinary` isn't that much of an advantage with PHP 8, unless you have a lot of data or a lot of duplicate data. Therefore we could make this optional and enable it via an environment variable.

What do you think?

**Comment by robertlemke** [comment]
Done, now it's disabled by default and you can enable it with PHP_IGBINARY_ENABLE

**Review by kdambekalns — APPROVED** [review]

**Review by kdambekalns — CHANGES_REQUESTED** [review]
Wait… should the `--enable-igbinary` lines in `build-sh` not be removed, now that the extension is built in `Dockerfile` separately?

Also, I see this during build:

```
=> => # configure: WARNING: unrecognized options: --enable-igbinary
```

**Comment by robertlemke** [comment]
I fixed that, should be fine now.

**Review by kdambekalns — APPROVED** [review]

**Pull request merged**
