### PR TITLE
Update to use flownative/docker/base:bullseye

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by robertlemke** [comment]
You mean "ready for review, this should work now with bullseye"? Should a take a look?

**Review by robertlemke — APPROVED** [review]
I compiled php and beach-php locally based on this PR and Neos works fine! I think we can dare to try this out for real.

**Comment by robertlemke** [comment]
Hmm, @kdambekalns even though I could compile this locally (with buildx), it now fails on Github:
https://github.com/flownative/docker-php/runs/5213605399?check_suite_focus=true

**Comment by kdambekalns** [comment]
Ok, it's the PHP version… fails with 7.2.34 locally as well. As does 7.3.33.

**Comment by kdambekalns** [comment]
Since 7.2 and 7.3 are no longer supported, maybe just drop them? 🤔

**Comment by robertlemke** [comment]
Yes, good idea. Since we don't support 7.2 and 7.3 in Beach anymore, we don't need to build nightlies etc. anymore.

**Comment by kdambekalns** [comment]
Will push updates soon…

**Pull request merged**
